### ISSUE TITLE
Beschrijving bij /bewoners niet juist en duidelijk voor periode

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#10]
Voor operatie /historie/bewoningen staat in de description:

> Het resultaat bevat de verblijfsplaatshistorie waarvan de EINDdatumgeldigheidverblijfsplaats op of na de datumVan ligt EN de BEGINdatum op of voor de DatumTotEnMet ligt.
> 
> Of
> 
> Het resultaat bevat de verblijfsplaats historie waarvan de begindatumgeldigheidverblijfsplaats voor op op de geldigOp ligt en de eindatumgeldigheidverblijfsplaats na of op de geldigOp ligt.
> 
> Als geldigOp is ingevuld mogen datumVan en datumTotenMet nietingevuld zijn.

Dit is niet in lijn met de parameters die zijn gedefinieerd: geldigvan, geldigtot, geldigop.

**Comment by JohanBoer** [comment]
Deze beschrijving is uit de Yaml verwijderd en de logica hiervoor zal in de een feature moeten worden beschreven. Zie ook #21
