### ISSUE TITLE
Uitbreiden scenario's bewoning overzicht

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#138]
- [x] als datum volledig onbekend is (00000000), zowel gevraagde als volgende
- [x] als binnen onzekerheidsperiode ook andere (wel zekere) wijziging is
- [x] datum aanvang 20220301, datum aanvang volgende 20220000, peildatum 2022-02-01, 2022-03-01, 2022-03-02
- [x] datum aanvang vorige 20220301, datum aanvang huidige 00000000, peildatum 2022-02-28, 2022-03-01
- [x] datum aanvang 20220301, datum aanvang volgende 20230000, peildatum gisteren, vandaag
- [ ] indicatieVeelBewoners
- [ ] bewoners op hoofd- en nevenadres
- [x] verblijfsobject met adres hernummering
- [x] verblijfsobject in samengevoegde gemeente

**Comment by MelvLee** [comment]
> * als datum volledig onbekend is (00000000), zowel gevraagde als volgende
> 
deze zijn toegevoegd

>     * als binnen onzekerheidsperiode ook andere (wel zekere) wijziging is (datum aanvang 20220301, datum aanvang volgende 20220000, peildatum 2022-02-01, 2022-03-01, 2022-2022-03-02

wat voor peildatum is 2022-2022-03-02?

ik vraag mij af hoever we moeten gaan met scenarios toevoegen. Er zijn 4 datum types wat betekent dat je op minimaal 16 situaties kan beschrijven. Volgens mij komt het er op neer dat in de onzekerheidsperiode een persoon mogelijke bewoner is en buiten de onzekerheidsperiode of bewoner is of geen bewoner

**Comment by fsamwel** [comment]
> ik vraag mij af hoever we moeten gaan met scenarios toevoegen.

goede vraag. in overzicht.feature niet denk ik. de features functioneren ook als test en daar wil ik ze wel graag in zien. dus ik stel voor dat we (ik) een mogelijke-bewoner-gba.feature maak met alle detail situaties

**Comment by fsamwel** [comment]
@CathyDingemanse @MelvLee 
Wat als datum aanvang is (geheel of gedeeltelijk) onbekend en peildatum ligt vóór de geboortedatum van de persoon of voor de datum eerste inschrijving GBA? Moeten we daar iets mee?

Bijvoorbeeld persoon woont op adres en alleen jaar 2022 van aanvang verblijf is bekend. Persoon is voor het eerst ingeschreven op 1 juli 2022 en we vragen bewoning op 1 januari 2022. Is het dan erg om deze persoon als mogelijke bewoner te leveren?

**Comment by fsamwel** [comment]
pull request #141 vult deel van de punten in

**Comment by fsamwel** [comment]
@fransrijkers in de HUP (3.7) lees ik bij infrastructurele wijzigingen:
> 08.10.30 Datum aanvang adreshouding
> Hier vult u de datum in waarop de infrastructurele wijziging is ingegaan.

Betekent dit dat de persoon een nieuwe aanvang adreshouding krijgt, terwijl de persoon niet fysiek verhuist? Is er een manier waarop we (voor bewoning) zouden kunnen herkennen dat de persoon niet daadwerkelijk verhuisd is? 
In deze situatie is het denk ik mogelijk dat de BAG identificaties ongewijzigd blijven, maar ook dat bijvoorbeeld alleen nummeraanduiding identificatie wijzigt en identificatie verblijfsobject hetzelfde.

Net zoiets speelt bij gemeentelijke herindeling. Dan wijzigt gemeente van inschrijving en datum aanvang, alle andere gegevens, inclusief de BAG-identificaties, blijven ongewijzigd. 

Worden deze wijzigingen in de BRP-V dan vertaald naar een nieuwe rij in lo3_adres (dus gezien als een ander adres)? Of wijzigt het adres (zelfde rij in lo3_adres met zelfde adres_id voor en na de hernummering/herindeling)?

**Comment by fransrijkers** [comment]
Bij zo'n infrastructurele wijziging wordt bij 08.72.10 Aangifte adreshouding dan een W ingevuld. Daaraan kun je zien dat het geen werkelijke verhuizing was. Staat ook in de HUP als je onderaan het lijstje in te vullen rubrieken kijkt. 
Verder is de wijziging inderdaad hetzelfde als een gewone verhuizing, dat maakt het onderscheid altijd een beetje lastig.
In 08.72.10 kan ook de waarde T voorkomen, van Technische wijziging. Die hebben we gebruikt voor de initiële koppeling met de BAG. Daarvoor geldt hetzelfde: persoon is niet verhuisd, maar er is wel een wijziiging van de categorie Verblijfplaats doorgevoerd.
Als vanaf 1 januari alle actuele adressen aan de BAG gekopppeld zijn, wordt het onderscheid makkelijker. Dan moet je aan de BAG-code kunnen zien dat het adresseerbaar object gelijk gebleven is, maar de nummer aanduiding gewijzigd is.
