### ISSUE TITLE
Geautomatiseerd valideren en resolven genereervariant + SDK's genereren. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#15]

**Comment by JohanBoer** [comment]
@MelvLee , de actions zijn allemaal gedefinieerd, maar ik kan ze niet handmatig starten. Ik heb de scripts zelf bekeken, maar ik kan niet zie waarin ze nu verschillen van de actons in bv. BRK-bevragen. Kan jij mij uitleggen wat ik moet veranderen of instellen om deze scripts ook handmatig te kunnen starten ?

**Comment by MelvLee** [comment]
Ik heb net bij de lint-oas.yml script voor de workflow_dispatch event aangegeven dat hij beschikbaar moet zijn voor alle branches, maar dat heeft niet geholpen. De enige manier om handmatig triggeren mogelijk te maken is de scripts naar de master branch brengen

**Comment by MelvLee** [comment]
@JohanBoer, ik heb een branch gemaakt met de commits van de workflow bestanden, zodat alleen die alvast naar de master branch kan worden gemerged. Daarna moet het mogelijk zijn om de workflows handmatig te starten.

**Comment by MelvLee** [comment]
@JohanBoer, de P.R. is gemerged. Als het goed is kan je nu de <kbd>Run workflow</kbd> zien.

**Comment by JohanBoer** [comment]
Werkt als een zonnetje.
