### ISSUE TITLE
descriptions

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#24]
- [x] Bewoning (API)
API voor het zoeken en raadplegen van bewoningen en metagegevens over bewoning (verloop). Een bewoning is een adresseerbaar object (verblijfsobject, ligplaats of standplaats) met ingeschreven bewoner(s). Iedere samenstelling van bewoners van het object is een bewoning. Overleden personen maken onderdeel uit van een bewoning tot het moment van overlijden. Gegevens over de bewoners zijn actueel.

Endpoints:

- [x] /bewoningen
Zoek bewoningen door een adresseerbaarObjectIdentificatie of een burgerservicenummer op te geven, samen met een peildatum of periode.

- [x] /bewoningen/{adresseerbaarObjectIdentificatie}
Raadpleeg een bewoning door een adresseerbaarobjectIdentificatie op te geven.

- [x] /bewoningen/{adresseerbaarObjectIdentificatie}/verloop
Raadpleeg het verloop van de bewoning van een adresseerbaar object over een periode door een adresseerbaarobjectIdentificatie en een periode op te geven. Het antwoord bevat het aantal verhuizingen van en naar het object en het gemiddelde aantal bewoners in de opgegeven periode.

**Comment by CathyDingemanse** [comment]
adresseerbaarObjectIdentificatie 
De unieke identificatie van een verblijfsobject, standplaats of ligplaats.

Bewoner
Een bewoner is een natuurlijk persoon die op een (verblijfs)object met een adres is ingeschreven of ingeschreven is geweest. 
datumAanvangAdreshouding : Datum waarop de bewoner van dit adresseerbaar object is ingeschreven.
datumTot : Datum waarop de bewoner van dit adresseerbaar object is uitgeschreven.

IndicatieVeelbewoners
Geeft aan dat het adresseerbaar object zo veel bewoners heeft of had in de gevraagde periode dat zij niet in het antwoord worden opgenomen, met uitzondering van de persoon waarvan de BSN is opgegeven. 

Verloop:
Inverhuizingen: 
Het aantal keren dat een alleenstaande of een gezin naar het verblijfsobject, de ligplaats of de standplaats is verhuisd binnen de opgegeven periode.

Uitverhuizingen:
Het aantal keren dat een alleenstaande of een gezin naar een ander verblijfsobject, ligplaats of standplaats is verhuisd binnen de opgegeven periode.

GemiddeldAantalBewoners
Het gemiddelde aantal bewoners van het verblijfsobject, de ligplaats of de standplaats in de gevraagde periode.

**Comment by CathyDingemanse** [comment]
AdresUitgebreid
Geen description

**Comment by CathyDingemanse** [comment]
Bewoner
Een bewoner is een persoon die op een (verblijfs)object met een adres is ingeschreven of ingeschreven is geweest.
datumAanvangAdreshouding : Datum waarop de bewoner van dit adresseerbaar object is ingeschreven.
datumTot : Datum waarop de bewoner van dit adresseerbaar object is uitgeschreven.

**Comment by JohanBoer** [comment]
> * Check descriptions op conformiteit met BRP bevragen. Bijvoorbeeld:
>   FunctieAdres: niet conform BRP bevragen

Nu verwijzing naar v1.2.0 gedaan

>   Geheimhouding Persoonsgegevens: niet conform BRPbevragen

Aangepast
