### ISSUE TITLE
Bewoningen zoeken op tegelijkertijd burgerservicenummer en identificatiecodenummeraanduiding

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#28]
Volgens de beschrijving in de OAS voor bewoningen kunnen parameters burgerservicenummer en identificatiecodenummeraanduiding tegelijkertijd worden gebruikt.

Ik zie het functionele nut daarvan niet. Dit levert altijd hetzelfde als alleen identificatiecodenummeraanduiding gebruiken, behalve wanneer de opgegeven persoon daar niet/nooit gewoond heeft (wat dan resulteert in geen enkele bewoning).

Dit maakt implementatie wel veel ingewikkelder, omdat de query voor het ophalen van medebewoners (zoeken op burgerservicenummer) er heel anders uitziet dan de query voor het ophalen van bewoners op adres (zoeken op identificatiecodenummeraanduiding).

Ik zou er daarom voor pleiten in de specificaties op te nemen dat één van de twee paramters gebruikt moet worden, niet allebei tegelijk.
Dus in plaats van "Ten minste één van de volgende parameters moet zijn opgenomen." zou ik zeggen " Eén van de volgende parameters moet zijn opgenomen."

**Comment by JohanBoer** [comment]
In de specs is bij "/bewoningen" nu de volgende description opgenomen : 
_Zoek bewoningen door een adresseerbaarObjectIdentificatie of een burgerservicenummer op te geven, samen met een peildatum of periode._
