### ISSUE TITLE
Als PO wil ik een feature van verloop

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#30]
...zodat gebruikers de de functionaliteit kunnen interpreteren, aanpassen en uitbreiden .

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Zie ook #72

**Comment by JohanBoer** [comment]
Zie ook #64
