### ISSUE TITLE
Als medewerker Sociale Zaken wil ik weten wie er op het adres van client wonen en wat hun relatie is

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#31]
...zodat ik kan bepalen of er sprake is van een gezin of een of meer kostendelers

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Op dit ogenblik levert een bevraging de bewoners van een adres in een periode op. De onderlinge relatie tussen de bewoners wordt niet in deze API geretourneerd. Wel worden de links naar de BRP-bevragen API meegeleverd van iedere bewoner. De relatie is dus te achterhalen door vervolg-calls op de BRP uit te voeren. M.I. zou dergelijke functionaliteit door de de consumer-software ingevuld moeten worden. Alle ingredienten zijn wel beschikbaar om deze informatiebehoefte in te vullen. 
@CathyDingemanse Is daarme deze functionele wens voldoende gefaciliteerd ?

**Comment by JohanBoer** [comment]
Herstel !!!!!!!   De persoonsgegevens van de medebewoners kunnen meegeleverd worden in de _embedded. Deze vraag is dus functioneel helemaal afgedekt m.i.
