### ISSUE TITLE
Als beheerder openbare ruimte wil ik met een punt op de kaart kunnen raadplegen wie daar woont

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#32]
...zodat ik bewoners kan aanspreken of contact met hen kan opnemen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dit zou kunnen door via de BAG een num-id op te zoeken en vervolgens de BRP te bevragen met de betreffende nummeraanduidingIdentificatie.
