### ISSUE TITLE
Als medewerker stadsontwikkeling wil ik alle bewoners van verblijfsobjecten in een pand opvragen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#35]
...zodat ik hen kan aanschrijven.

**Acceptatiecriteria**
- bewoners van meer verblijfsobjecten tegelijk kunnen opvragen 

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dit is nu mogelijk door het endpoint /panden/{pandidentificatie} of als je wilt zoeken /panden van de HC-API BAG Huidige Bevragen te gebruiken. 

Daarmee krijg je van een pand alle adresseerbaarObjectIdentificaties van verblijfsobjecten in het betreffende pand. 

Als je dan in 1 call alle bewoningen met bewoners wilt opvragen dan zou de query-parameter "adresseerbaarObjectIdentificatie" moeten worden gewijzigd in een array. 

@CathyDingemanse : Is deze invulling voor deze functionaliteit afdoende ? Ik denk dat het opleveren van alle bewoners op basis van de pandIdentificatie een brug te ver is voor deze API. (Dat zou dan namelijk een API zijn die over 2 Basisregistraties heen gaat. )
