### ISSUE TITLE
Als medewerker bijstandverlening zelfstandigen wil ik weten wie in welke periode met aanvrager heeft samengewoond 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#38]
...zodat ik kan bepalen of de kostendelersnorm van toepassing was en evt. kan terugvorderen

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Van iedere bewoner wordt in de _embedded de set properties van de corresponderende persoon opgenomen inclusief links naar ouders kinderen en partners.  Daarmee zijn de gegevens beschikbaar om de bovenstaande informatie uit de response te halen. Vraag is of dit voldoende consumer-friendly is en of dit eventueel makkelijker te leveren is. Onderwerp voor een ontwerp-sessie.

**Comment by JohanBoer** [comment]
Zoals deze issue nu geformuleerd is wordt de gewenste functionaliteit afgedekt door de huidige API-specificatie.
