### ISSUE TITLE
Als beheerder openbare ruimte wil ik weten wie op een perceel woont 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#39]
zodat ik deze persoon of personen kan aanspreken over een klacht of melding openbare ruimte.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dia kan via de BRK opgevraagd worden door van een perceel de appartmentsrechen en de bijbehorende nummeraanduidingen-id's. Met die nummeraanduiding-id's wordt de BRP-bevraging.
