### ISSUE TITLE
Als medewerker vergunningen wil ik de gemiddelde bewoningduur weten op een adres binnen een bepaalde periode

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#64]
..zodat ik onregelmatigheden op een adres kan signaleren bij het verlenen van een vergunning.

**Acceptatiecriteria**
- gemiddelde bewoningduur in maanden op een adres van een gezin of alleenstaande gedurende een op te geven periode
- met een gezin wordt bedoeld: een groep personen die zich op dezelfde datum op het adres hebben gevestigd EN indien vertrokken op dezelfde datum van het adres zijn vertrokken.
- (uniek) adres geef je op in het pad (zie VNG-Realisatie/Haal-Centraal-BRP-bevragen#402) met de periode als query parameter.

**Definition of done**
- [x] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Hiervoor wordt de property gemiddeldeBewoningduur toegevoegd bij Verloop.  Dat ga ik in de specificatie aanbrengen. 

@MelvLee : Wil jij de berekening hiervan opnemen in verloop.feature 
@fsamwel : Doen jullie hier al iets mee in Den Haag ? of moet deze berekening eerst vastgesteld worden. 

Is het voorstel van @CathyDingemanse hier afdoende ? 
Ik vraag me bijvoorbeeld af of de bewoningsduur van een alleenstaande of gezin die buiten de opgegeven query-periode valt in zijn geheel meetelt (Dus in een periode van 1 jaar zou je kunnen uitkomen op een gemiddeldeBewoningDuur van 3 jaar).
Of telt alleen de bewoningduur binnen de query-periode mee ? 

Zie eventueel ook #72 mbt de gemiddeld aantal bewoners.

**Comment by fsamwel** [comment]
> Doen jullie hier al iets mee in Den Haag ? of moet deze berekening eerst vastgesteld worden.

Dit veld bestaat nog niet in onze implementatie. Moeten wij dan ook toevoegen.

**Comment by fsamwel** [comment]
Bij een gezin dat een kind krijgt, wordt in bovenstaande beschrijving het kind niet tot het gezin gerekend. Op het adres zijn er dan twee personen/gezinnen.

Bijvoorbeeld twee personen gaan op 1-1-2019 op een adres wonen. Op 26-12-2020 wordt hun kind geboren.
De gemiddeldeBewoningduur voor periode 1-1-2020 t/m 31-12-2020 van de ouders is 731 dagen. 
De gemiddeldeBewoningduur voor periode 1-1-2020 t/m 31-12-2020 van het kind is 5 dagen.

Wordt gemiddeldeBewoningduur een array met de bewoningsduren van alle gezinnen of personen? Of wordt een gemiddelde berekend? En wordt in dat laatste geval rekening gehouden met de gezinsgrootte?
Dus voor bovenstaande familie (731+5)/2=368? Of (731*2 + 5*1)/3=489?

@CathyDingemanse maakt dat uit hoe het precies berekend wordt of gaat het alleen om het signaleren van extreme situaties (bijvoorbeeld gemiddelde bewoningsduur over een langere periode is lager dan 3 maanden)

**Comment by fsamwel** [comment]
> Ik vraag me bijvoorbeeld af of de bewoningsduur van een alleenstaande of gezin die buiten de opgegeven query-periode valt in zijn geheel meetelt

Ik zou zeggen in zijn geheel. 
Anders wordt het veel lager door een verhuizing aan het begin of einde van de gevraagde periode, terwijl de personen wel lang op het adres hebben gewoond. Het is geen indicatie van onregelmatigheid dat een bewoner in januari of december verhuist i.p.v. in juli (als je een heel kalenderjaar bevraagt). Door alleen rekenen met de bewoningsduur binnen de periode de betrouwbaarheid van het gemiddelde als indicatie voor onregelmatigheden lager. 
Bijvoorbeeld bij een periode van 3 maanden leidt één verhuizing al tot een gemiddelde bewoningduur van 1.5 maanden, ook wanneer zowel de oude als nieuwe bewoner lang op het adres blijven.

**Comment by fsamwel** [comment]
Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bewoning/issues/57. Destijds hebben we hier ook al over gesproken. Mijn opmerking destijds:
> bewoningsduur kan een sterk vertekend beeld geven wanneer ook de bewoning voor en na de periode wordt meegerekend, bijvoorbeeld wanneer eerst een bewoner heel lang op het adres staat ingeschreven en er daarna heel veel in- en uitverhuizingen (korte bewoning) is. Het lang wonen verdoezelt dan de korte bewoning erna.
> Ook wanneer alleen bewoning binnen de periode wordt meegeteld kan een vertekend beeld ontstaan.
> Het is niet duidelijk hoe de bewoningsduur moet worden berekend om als aanvullende informatie te dienen bovenop in- en uitverhuizingen. Daarom kan de bewoningsduur worden verwijderd

Daarna is bewoningsduur verwijderd in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/582

**Comment by JohanBoer** [comment]
Goed dat je je dat nog hebt weten te achterhalen Frank. 
@CathyDingemanse Conclusie is dus: niet opnemen in de OAS, feature niet aanpassen. Issue was al afgehandeld.  Eens ?

**Comment by CathyDingemanse** [comment]
Eens.
