### ISSUE TITLE
Als medewerker riolering wil ik weten het aantal inwoners is van een pand

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#71]
zodat ik kan berekenen hoeveel afvalwater het riool te verwerken krijgt

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Ik weet niet waarom dit issue is heropend. gemiddeldAantalBewoners zit nog steeds in verloop.
