### ISSUE TITLE
Als medewerker vergunningen wil ik het aantal verhuisbewegingen weten op een adres binnen een bepaalde periode

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#72]
...zodat ik onregelmatigheden op een adres kan signaleren bij het verlenen van een vergunning.

**Acceptatiecriteria**
Veranderd n.a.v. de wijziging van bewoning resource naar bewoners resource!
- geeft bij input nummeraanduiding en periode een response met het aantal inschrijvingen en uitschrijvingen op een adres gedurende de opgegeven periode
- waarbij het aantal bewoners dat zich op dezelfde datum heeft ingeschreven wordt samengenomen tot 1 inschrijving 
- waarbij het aantal bewoners dat zich op dezelfde datum heeft  uitgeschreven wordt samengenomen  tot 1 uitschrijving.

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Is geïmplementeerd in de endpoint /bewoningen/{identificatiecodenummeraanduiding}/verloop.

**Comment by MelvLee** [comment]
In het verloop is er een kenmerk gemiddeldAantalBewoners. Hoe moet dit worden bepaald? De description zegt: gemiddeld aantal bewoners in de gevraagde periode. Stel: de periode is 01-12 t/m 31-12. In die periode was aantal bewoners tussen 01-12 en 10-12 gelijk aan 3 en tussen 11-12 en 31-12 gelijk aan 4. Is het dan (3+4)/2=3.5 of (3/31*10)+(4/31*21)=2.7

**Comment by fsamwel** [comment]
het gemiddeld aantal bewoners moet worden berekend rekening houdend met de duur van de bewoning.

dus zou ik gemiddelde berekenen als: (3*10 + 4*21)/31=3,68

**Comment by MelvLee** [comment]
(3/31\*10)+(4/31\*21). Bijna hetzelfde als jij, alleen andere volgorde. Maar wat ik hier probeer duidelijk te maken is dat als de periode langer is, maar de aantallen bewoners blijft gelijk, dan krijgt je bij mijn manier 1 dezelfde waarde, maar voor manier 2 een andere waarde terwijl het aantal bewoners niet is veranderd.
v.b. nu berekenen tussen 1-10 en 31-12. aantal bewoners tussen 1-10 en 10-12 = 3 en tussen 11-12 en 31-12 = 4, dan is gemiddeld aantal bewoners bij mijn manier 1 nog steeds 3.5 en bij mijn manier 2: (3/(31+30+31)\*(31+30+10))+(4/(31+30+31)\*(31+30+21))=3.57 en in jouw geval denk ik: ((3\*31)+(3\*30)+(3\*10)+(4\*21))/(31+30+31)=92

**Comment by MelvLee** [comment]
Eerste aanzet van feature: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bewoning/blob/develop/features/verloop.feature
Als we uit zijn hoe gemiddeld aantal bewoners moet worden berekend, zal ik de features uitbreiden

**Comment by fsamwel** [comment]
In de implementatie in Den Haag wordt het berekend vanuit de bewoners, dus voor elke bewoner de tijdsduur/totaletijdsduur.

Dus in je voorbeeld met gevraagde periode 01-12-2020 t/m 31-12-2020:
| Bewoner | Dat.Aanvang | Dat. Einde | tijdsduur in periode | tijdsduur/totaletijdsduur |
|--- |--- |--- |--- |--- |
| Henk  | 15-08-2007 | - | 31 | 1 |
| Ingrid | 04-03-2010 | - | 31 | 1 |
| Tom   | 27-11-2019 | - | 31 | 1 |
|  Sanne | 11-12-2020 | - | 21 | 0.6774 |

Als je deze waarden van alle bewoners bij elkaar optelt krijg je het gemiddeld aantal bewoners van 3.6774

**Comment by fsamwel** [comment]
In de feature wordt gesproken over een "inschrijfdatum". Die kennen we niet. Ik denk dat de datumAanvangAdreshouding moet worden gebruikt als begindatum.
Een uitschrijfdatum bestaat niet binnen de GBA, die berekenen we (in onze verblijfplaatshistorie resource) in veld datumTot (= de datumAanvangAdreshouding van de volgende verblijfplaats van deze persoon).
Het is wellicht handig om de begrippen te definiëren of de begrippen uit LO GBA/BRP te gebruiken.

**Comment by fsamwel** [comment]
Voor berekening van verloop moet in de feature ook iets gezegd worden over omgaan met open periodes. Bijvoorbeeld als je alleen datumTotEnMet gebruikt zonder datumVan. Het grootste deel van de eeuwigheid heeft er niemand op het adres gewoond (bestond het adres nog niet), dus is het gemiddeldAantalBewoners dan astronomisch klein.
Ik stel voor in dat geval te rekenen vanaf de eerste bewoner. In het bovenstaande voorbeeld als Henk de eerste bewoner is van het adres, dan wordt gemiddeldAantalBewoners berekend vanaf 15-08-2007. De totale duur van de bewoonde periode is dan 4887 dagen.

Dus in je voorbeeld met gevraagde periode t/m 31-12-2020 (zonder datumVan):
| Bewoner | Dat.Aanvang | Dat. Einde | tijdsduur in periode | tijdsduur/totaletijdsduur |
|--- |--- |--- |--- |--- |
| Henk  | 15-08-2007 | - | 31 | 1 |
| Ingrid | 04-03-2010 | - | 31 | 0.8093 |
| Tom   | 27-11-2019 | - | 31 | 0.0818 |
|  Sanne | 11-12-2020 | - | 21 | 0.0041 |

Bij elkaar opgeteld wordt dan het gemiddeldAantalBewoners 1.8952

Wanneer alleen de datumVan wordt opgegeven en dus geen datumTotEnMet, moet verloop worden berekend met als datumTotEnMet de datum van vandaag.

**Comment by MelvLee** [comment]
Update van verloop feature: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bewoning/blob/develop/features/verloop.feature

Eerste aan gemiddeld aantal bewoners feature: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bewoning/blob/develop/features/gemiddeld-aantal-bewoners.feature

**Comment by fsamwel** [comment]
@MelvLee in dit scenario:
```
    En er is 1 bewoner met datum tot '<datum tot>' op het adresseerbaar object
    Als voor adresseerbaar object met identificatie 1234 het verloop tussen 01-12-2020 en 31-12-2020 wordt bevraagd
    Dan is het aantal inverhuizingen gelijk aan 0
    En is het aantal uitverhuizingen gelijk aan 1

    Voorbeelden:
    | datum tot  | omschrijving |
    | 14-12-2020 | datum tot valt binnen de opgegeven periode |
    | 01-12-2020 | datum tot valt op de eerste dag van de opgegeven periode |
    | 31-12-2020 | datum tot valt op de laatste dag van de opgegeven periode |
```
Ik denk dat we de definitie van datumTot in bewoningen gelijk moeten houden aan die in verblijfplaatshistorie. In de [verblijfplaatshistorie.feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/blob/master/features/verblijfplaatshistorie.feature) staat: "Bij een historische verblijfplaats wordt een datumTot opgenomen, die gelijk is aan de datum aanvang adreshouding van de daarop volgende (actuele of historische) verblijfplaats."

Als datumTot=01-12-2020, dan woont de persoon al op 01-12-2020 op een ander adres. Dus heeft de persoon in de periode niet op dit adres gewoond. Als je /bewoningen/{identificatiecodenummeraanduiding} doet zal je deze (uitverhuizende) persoon ook niet terugkrijgen. Ik zou het niet consistent binnen de API vinden wanneer het berekenen van verloop personen meerekent die bij het vragen om de lijst van bewoners in de periode niet worden geleverd.
Dus bij datumVan==datumTot (en geen andere bewoners) verwacht ik inverhuizingen=0 en uitverhuizingen=0 en gemiddeldAantalBewoners=0

**Comment by fsamwel** [comment]
@MelvLee kan je ook nog iets opnemen over geheel of gedeeltelijk onbekende datums (betreft m.n. datumAanvangAdreshuiding en daarmee ook datumTot)?

**Comment by MelvLee** [comment]
> 
> 
> @MelvLee in dit scenario:
> 
> ```
>     En er is 1 bewoner met datum tot '<datum tot>' op het adresseerbaar object
>     Als voor adresseerbaar object met identificatie 1234 het verloop tussen 01-12-2020 en 31-12-2020 wordt bevraagd
>     Dan is het aantal inverhuizingen gelijk aan 0
>     En is het aantal uitverhuizingen gelijk aan 1
> 
>     Voorbeelden:
>     | datum tot  | omschrijving |
>     | 14-12-2020 | datum tot valt binnen de opgegeven periode |
>     | 01-12-2020 | datum tot valt op de eerste dag van de opgegeven periode |
>     | 31-12-2020 | datum tot valt op de laatste dag van de opgegeven periode |
> ```
> 
> Ik denk dat we de definitie van datumTot in bewoningen gelijk moeten houden aan die in verblijfplaatshistorie. In de [verblijfplaatshistorie.feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-historie-bevragen/blob/master/features/verblijfplaatshistorie.feature) staat: "Bij een historische verblijfplaats wordt een datumTot opgenomen, die gelijk is aan de datum aanvang adreshouding van de daarop volgende (actuele of historische) verblijfplaats."
> 
> Als datumTot=01-12-2020, dan woont de persoon al op 01-12-2020 op een ander adres. Dus heeft de persoon in de periode niet op dit adres gewoond. Als je /bewoningen/{identificatiecodenummeraanduiding} doet zal je deze (uitverhuizende) persoon ook niet terugkrijgen. Ik zou het niet consistent binnen de API vinden wanneer het berekenen van verloop personen meerekent die bij het vragen om de lijst van bewoners in de periode niet worden geleverd.
> Dus bij datumVan==datumTot (en geen andere bewoners) verwacht ik inverhuizingen=0 en uitverhuizingen=0 en gemiddeldAantalBewoners=0

scenario is aangepast n.a.v. opmerking Frank

**Comment by MelvLee** [comment]
> 
> 
> @MelvLee kan je ook nog iets opnemen over geheel of gedeeltelijk onbekende datums (betreft m.n. datumAanvangAdreshuiding en daarmee ook datumTot)?

Kan hier dezelfde logica voor leeftijd bepaling worden toegepast?

- als datumAanvangAdreshouding jaar = 2019, maand = 6 en dag = onbekend, dan wordt voor verloop 2019-07-01 als datumAanvangAdreshouding gehanteerd
- als datumAanvangAdreshouding jaar = 2019 en maand en dag = onbekend, dan wordt 2020-01-01 als datumAanvangAdreshouding gehanteerd

Ik weet alleen niet wat als default datum moet worden gebruikt bij volledig onbekend datumAanvangAdreshouding

**Comment by fsamwel** [comment]
Bijvoorbeeld bij verloop in periode 2020-10-15 t/m 2020-11-2020:
Datum aanvang=2020 (dag en maand onbekend): is deze persoon voor, tijdens of na de periode inverhuisd?
Datum aanvang=2020-10 (dag onbekend): is deze persoon voor of tijdens de periode inverhuisd?
Datum aanvang=2020-11 (dag onbekend): is deze persoon tijdens of na de periode inverhuisd?
Datum tot=2020 (dag en maand onbekend): is deze persoon voor, tijdens of na de periode uitverhuisd?
Datum tot=2020-10 (dag onbekend): is deze persoon voor of tijdens de periode uitverhuisd?
Datum tot=2020-11 (dag onbekend): is deze persoon tijdens of na de periode uitverhuisd?

Mijn conclusie is dat bij (gedeeltelijk) onbekende datum aanvang of datum tot we helemaal niks kunnen zeggen wat betreft verloop, althans niet met betrekking tot deze persoon. Ik zou zeggen dat we de bewoning van deze betreffende persoon volledig negeren in de berekening van verloop, wanneer de onzekerheidsperiode van de aanvang of datumTot binnen de gevraagde periode valt.
Voor het bereken van gemiddeld aantal bewoners zou je nog kunnen pleiten voor het aannemen van het midden van de onzekerheidsperiode (1 juli of 15e van de maand) in de berekening.

**Comment by MelvLee** [comment]
Komt het voor dat datumAanvangAdreshouding (gedeeltelijk) onbekend is voor een verblijfplaats op een binnenland adres? Ik weet niet hoe precies verloop wordt gebruikt voor het bepalen van onregelmatigheden, maar als een (gedeeltelijk) onbekend datumAanvangAdreshouding niet terugkomt in verloop, dan kan je ervoor zorgen dat op een adres alleen personen wordt ingeschreven met gedeeltelijk onbekend datumAanvangAdreshouding

**Comment by fsamwel** [comment]
> Komt het voor dat datumAanvangAdreshouding (gedeeltelijk) onbekend is voor een verblijfplaats op een binnenland adres?

Het kan in ieder geval voorkomen volgens LO GBA. Wat mogelijk ook kan voorkomen is een (gedeeltelijk) onbekende datumAanvangAdreshouding van het volgende verblijf, bijvoorbeeld bij vertrek naar het buitenland. Dan krijgt het binnenlandse adres een (gedeeltelijk) onbekende  datumTot.

Het LO GBA zegt het zo:
| Elementnaam | Datum aanvang adreshouding |
|--- |--- |
| Toelichting | De datum van aangifte of ambtshalve melding van verblijf en adres. Bij een aangifte van verblijf en adres is dit de aangiftedatum. Bij een tijdige aangifte (tussen vier weken voor en vijf dagen na de verhuizing) van vestiging op het adres is dit de in de aangifte vermelde datum van adreswijziging. Bij een niet tijdige aangifte is dit de aangiftedatum. Bij inschrijving op grond van een geboorteakte is dit de geboortedatum. Bij ambtshalve inschrijving is dit de datum waarop de betrokkene schriftelijk van het voornemen van ambtshalve opneming mededeling is gedaan. |
| Lengte | 8 |
| Type | Numeriek |
| Standaardwaarde | 00000000 |
| Mogelijke waarden | jjjjmmdd, jjjjmm00, jjjj0000, 00000000 |

**Comment by CathyDingemanse** [comment]
Ik lees hierin dat een aanvang adreshouding in NL en bij vertrek naar het buitenland per definitie volledig bekend is in de BRP. Alle in het LO genoemde datums in de tekst zijn volledig (de datum dat de brief is gestuurd, de datum dat aangifte is gedaan, de datum op de geboorteakte, etc.).

**Comment by fsamwel** [comment]
In de testdata van het GBA-V zitten verschillende voorbeelden met volledig onbekende of gedeeltelijk onbekende datum aanvang adreshouding.
@gertjanvanderkooij weet jij of dit echt voor komt?

**Comment by gertjanvanderkooij** [comment]
Zal voornamelijk voorkomen in (oudere) adreshistorie, mogelijk incidenteel (handje vol?) in actuele adressen van personen.
Is mogelijk wel een check bij de zelfevaluatie BRP door gemeenten. Dit na te vragen bij RvIG.

**Comment by MelvLee** [comment]
> 
> 
> Bijvoorbeeld bij verloop in periode 2020-10-15 t/m 2020-11-2020:
> Datum aanvang=2020 (dag en maand onbekend): is deze persoon voor, tijdens of na de periode inverhuisd?
> Datum aanvang=2020-10 (dag onbekend): is deze persoon voor of tijdens de periode inverhuisd?
> Datum aanvang=2020-11 (dag onbekend): is deze persoon tijdens of na de periode inverhuisd?
> Datum tot=2020 (dag en maand onbekend): is deze persoon voor, tijdens of na de periode uitverhuisd?
> Datum tot=2020-10 (dag onbekend): is deze persoon voor of tijdens de periode uitverhuisd?
> Datum tot=2020-11 (dag onbekend): is deze persoon tijdens of na de periode uitverhuisd?
> 
> Mijn conclusie is dat bij (gedeeltelijk) onbekende datum aanvang of datum tot we helemaal niks kunnen zeggen wat betreft verloop, althans niet met betrekking tot deze persoon. Ik zou zeggen dat we de bewoning van deze betreffende persoon volledig negeren in de berekening van verloop, wanneer de onzekerheidsperiode van de aanvang of datumTot binnen de gevraagde periode valt.
> Voor het bereken van gemiddeld aantal bewoners zou je nog kunnen pleiten voor het aannemen van het midden van de onzekerheidsperiode (1 juli of 15e van de maand) in de berekening.

Features zijn uitgebreid met geheel of gedeeltelijk onbekend datum aanvang adreshouding en datum tot
