### ISSUE TITLE
identificatiecodeVerblijfplaats ontbreekt in Bewoning

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bewoning#8]
In Bewoning zit geen property identificatiecodeVerblijfplaats. Deze had ik hier wel verwacht.

**Comment by CathyDingemanse** [comment]
@Robkromwijk je hebt gelijk. Wij gaan de ADO ID opnemen als padparameter. Thnx!!!

**Comment by JohanBoer** [comment]
@CathyDingemanse 
Even een check: 
Ik ga dus   /bewoningen/{nummeraanduidingIdentificatie} vervangen door   /bewoningen/{adresseerbaarObjectAanduiding}
 en 
  /bewoningen/{nummeraanduidingIdentificatie}/verloop vervangen door   /bewoningen/{adresseerbaarObjectAanduiding}/verloop

Akkoord ?

**Comment by CathyDingemanse** [comment]
akkoord!
